name: TON Connect 2.0 Support Request
description: Request a support regarding TON Connect 2.0 implementation
labels: 'TON Connect 2.0'
body:
  - type: markdown
    attributes:
      value: |
        Thank you for supporting new wallet-apps communication standard!

        Create issue with this template to apply for a grant related to TON Connect 2.0.
  - type: input
    attributes:
      label: "Name"
      description: "What's the name of your wallet?"
      placeholder: "ex. Very Generic TON Wallet"
    validations:
      required: False
  - type: input
    id: contact
    attributes:
      label: Telegram Contact
      description: How can we get in touch with you if we need more info?
      placeholder: ex. @tonkongz
    validations:
      required: True
  - type: input
    attributes:
      label: "Link to demo"
      description: 'Link to the demo video showing that standard is supported'
      placeholder: ex. https://t.me/toncoin/399
    validations:
      required: True
  - type: textarea
    attributes:
      label: "Amount"
      placeholder: |
        up to 5,000 USD worth of TON 
    validations:
      required: True
